- name: Set permissions on ~/.ssh
  file:
    path: '~/.ssh'
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    recurse: true 
    mode: '0700'
  become: true

- name: Set permissions for ~/.ssh files
  
  file:
    path: "{{ item }}"
    mode: '0600'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  become: true
  with_fileglob:
    - "~/.ssh/*"

- name: Setup and start ssh-agent
  shell: |
    ssh-add
    eval "$(ssh-agent)"
