feeds:
  - name: "Lawrence Person's BattleSwarm Blog"
    link: "https://www.battleswarmblog.com/"
    url: "https://www.battleswarmblog.com/?feed=rss2"
    column: 1
  - name: "Cafe Hayek"
    link: "https://cafehayek.com/"
    url: "https://cafehayek.com/feed"
    column: 1
  - name: "Real Clear Politics"
    link: "https://www.realclearpolitics.com/"
    url: "https://www.realclearpolitics.com/index.xml"
    column: 2
  - name: "Instapundit"
    link: "https://instapundit.com/"
    url: "https://instapundit.com/feed/"
    column: 3
  - name: "Twitchy"
    link: "https://twitchy.com/"
    url: "https://twitchy.com/feed"
    column: 3