bookmarks:
  - title: Ali Express
    url: https://www.aliexpress.com/
  - title: Amazon
    url: https://www.amazon.com/
  - title: ChatGPT
    url: https://chat.openai.com/
  - title: ClaudeGPT
    url: https://anthropic.com/claude
  - title: GrokGPT
    url: https://chat.grok.com/
  - title: Cloudflare
    url: https://www.cloudflare.com/
  - title: Codeword Generator
    url: https://cxxr.github.io/nsa.js/
  - title: Ebay
    url: https://www.ebay.com/
  - title: Gists
    url: https://gist.github.com/
  - title: Github
    url: https://github.com/
  - title: Is There Any Deal
    url: https://isthereanydeal.com/
  - title: MoneroOcean
    url: https://moneroocean.stream/#/dashboard?addr=47JaiTVAxoujSKhibhmTS3hHaN8mW6Jfr46N1msSBsFhAyJj91KJ2maEk3DMf6gM9Ndmx81CqPAo41XPakFM3NTpUtn9dxL
  - title: Office 365
    url: https://www.office.com/
  - title: Slickdeals
    url: https://slickdeals.net/
  - title: Teams
    url: https://teams.microsoft.com/
  - title: Tailscale
    url: https://tailscale.com/
  - title: Thingiverse
    url: https://www.thingiverse.com/
    