headers:
  - name: "Docs"
    link: "https://docs.google.com/"
  - name: "Gmail"
    link: "https://mail.google.com/mail/u/0/"
  - name: "Maps"
    link: "https://www.google.com/maps"
  - name: "Youtube"
    link: "https://www.youtube.com/"

feeds:
  - name: "Lawrence Person's BattleSwarm Blog"
    link: "https://www.battleswarmblog.com/"
    url: "https://www.battleswarmblog.com/?feed=rss2"
    column: 1
  - name: "Cafe Hayek"
    link: "https://cafehayek.com/"
    url: "https://cafehayek.com/feed"
    column: 1
  - name: "Slashdot"
    link: "https://slashdot.org/"
    url: "https://rss.slashdot.org/Slashdot/slashdotMain"
    column: 1
    summary: false
  - name: "Real Clear Politics"
    link: "https://www.realclearpolitics.com/"
    url: "https://www.realclearpolitics.com/index.xml"
    column: 2
  - name: "Instapundit"
    link: "https://instapundit.com/"
    url: "https://instapundit.com/feed/"
    column: 3
  - name: "Twitchy"
    link: "https://twitchy.com/"
    url: "https://twitchy.com/feed"
    column: 3